<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc4b25d4c67ba5f31d25bdba015db7cda
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc4b25d4c67ba5f31d25bdba015db7cda::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc4b25d4c67ba5f31d25bdba015db7cda::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc4b25d4c67ba5f31d25bdba015db7cda::$classMap;

        }, null, ClassLoader::class);
    }
}
