<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5d07896bb40c3a7a3f0e39a291f391ff
{
    public static $prefixesPsr0 = array (
        'F' => 
        array (
            'Flow' => 
            array (
                0 => __DIR__ . '/..' . '/flowjs/flow-php-server/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit5d07896bb40c3a7a3f0e39a291f391ff::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit5d07896bb40c3a7a3f0e39a291f391ff::$classMap;

        }, null, ClassLoader::class);
    }
}
