<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1638dd60b5dc71c5a8439ecb2ee2a15e
{
    public static $prefixesPsr0 = array (
        'F' => 
        array (
            'Flow' => 
            array (
                0 => __DIR__ . '/..' . '/flowjs/flow-php-server/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit1638dd60b5dc71c5a8439ecb2ee2a15e::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit1638dd60b5dc71c5a8439ecb2ee2a15e::$classMap;

        }, null, ClassLoader::class);
    }
}
