<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Flow' => array($vendorDir . '/flowjs/flow-php-server/src'),
);
