<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit37994d6d58c55bdfbe8351c966474001
{
    public static $prefixLengthsPsr4 = array (
        'l' => 
        array (
            'lbuchs\\WebAuthn\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'lbuchs\\WebAuthn\\' => 
        array (
            0 => __DIR__ . '/..' . '/lbuchs/webauthn/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit37994d6d58c55bdfbe8351c966474001::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit37994d6d58c55bdfbe8351c966474001::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit37994d6d58c55bdfbe8351c966474001::$classMap;

        }, null, ClassLoader::class);
    }
}
